= Cluster ingress

== Problem

We need to decide how workloads on VSHN Managed Talos clusters are exposed over HTTP and HTTPS.
Since Kubernetes offers both the Ingress API and Gateway API, we also need to decide which APIs we support for the initial release.

=== Goals

* Select an ingress implementation for VSHN Managed Talos clusters
* Expose workloads over HTTP and HTTPS
* Support automated TLS certificate issuance and renewal with cert-manager

=== Non-Goals

* Support for service type `LoadBalancer`
* Support for Gateway API // Let's see if we keep this.

== Proposals

=== Cilium Ingress controller

Cilium provides an https://docs.cilium.io/en/v1.18/network/servicemesh/ingress/[Ingress controller] that implements the Kubernetes Ingress API and uses Envoy to proxy traffic.

Cilium can expose all `Ingress` resources through a shared `LoadBalancer` Service or create a dedicated `LoadBalancer` Service for each `Ingress` resource.
Using either mode requires the infrastructure to provide an implementation for `LoadBalancer` Services.
The dedicated mode gives us the option to offer dedicated `LoadBalancer` Services for selected `Ingress` resources in the future.
Cilium can also accept the https://docs.cilium.io/en/v1.18/helm-reference/[PROXY protocol] on all Ingress listeners.
This is a controller-wide setting, and enabling it causes the listeners to accept only PROXY protocol traffic.

Cert-manager works with the Cilium Ingress controller, with one caveat from our initial testing.
In our tested configuration with Cilium's HTTPS enforcement enabled, an `Ingress` resource using an ACME HTTP-01 challenge requires `acme.cert-manager.io/http01-edit-in-place: "true"`.
This annotation makes cert-manager modify the existing `Ingress` resource instead of creating a separate solver resource.
It works around https://github.com/cilium/cilium/issues/35347[a known Cilium issue with HTTPS enforcement for multiple `Ingress` resources using the same hostname].

NOTE: During initial testing, we haven't been able to access the Cilium ingress running on an IPv4 single stack cluster when connecting over IPv6 to a load balancer which has a IPv6 public IP and which forwards the client IP to the ingress controller via PROXY protocol.

=== Cilium Gateway API implementation

Cilium also provides https://docs.cilium.io/en/v1.18/network/servicemesh/gateway-api/gateway-api/[Gateway API support] for HTTP and HTTPS traffic.
https://cert-manager.io/docs/usage/gateway/[cert-manager can issue certificates for `Gateway` resources].

Cilium is actively working on improving their Gateway API implementation.
Support for https://github.com/cilium/cilium/pull/46303[`ListenerSet`] and https://github.com/cilium/cilium/pull/46184[`TCPRoute` and `UDPRoute`] have been merged, and are available in https://github.com/cilium/cilium/releases/tag/v1.20.0[Cilium 1.20].

Finally, cert-manager can https://cert-manager.io/docs/usage/gateway/[issue certificates for `Gateway` resources with an appropriate configuration].
Starting with version 1.20, cert-manager also supports the Gateway API `ListenerSet` CRD.


=== kgateyway
// TODO

=== HAProxy Ingress
// TODO

== Decision

We use Cilium as the ingress implementation for VSHN Managed Talos.
Initially, VSHN Managed Talos will only support the Kubernetes Ingress API through the Cilium Ingress controller, using Cilium's shared load-balancer mode.
However, we plan to offer Gateway API support via Cilium's Gateway API implementation in the future.

== Rationale

Cilium meets the requirements for VSHN Managed Talos's ingress.
Additionally, since we already use Cilium as the CNI for VSHN Managed Talos, we don't have to maintain and operate an additional software for the ingress on VSHN Managed Talos.

Finally, while Cilium's ingress controller integrates with cert-manager, there is room for improvements: HTTP 01 challenges only work when configuring the challenge path directly in the target `Ingress` resource.
While this isn't great (especially for `Ingress` resources that are managed via GitOps), we believe it should be possible to fix this shortcoming

While it would be nice to offer Gateway API by default from the start, it's not strictly necessary to do so.
Additionally, we don't have that much information regarding which Gateway API features are actually relevant to customers, so it makes more sense to defer choosing a Gateway API implementation until we have some customer insights.
Also, while the Kubernetes Ingress API isn't getting developed anymore, and new features only land in Gateway API, it's stable and covers the basic features that are required to expose a simple application. From the operational perspective, only supporting the Kubernetes Ingress API keeps the test and support surface small.
Since Cilium provides a reasonable Gateway API implementation, it's likely that we'll end up going with Cilium's implementation if and when we decide to offer a Gateway API implementation by default.

IPv6 and dual-stack ingress aren't required for the initial release, and we haven't yet validated a working IPv6 setup.
We will revisit IPv6 support separately after the initial release.

== References

* https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes: Ingress]
* https://gateway-api.sigs.k8s.io/[Kubernetes Gateway API]
* https://docs.cilium.io/en/v1.18/network/servicemesh/ingress/[Cilium 1.18: Kubernetes Ingress support]
* https://docs.cilium.io/en/v1.18/network/servicemesh/gateway-api/gateway-api/[Cilium 1.18: Gateway API support]
* https://cert-manager.io/docs/usage/ingress/[cert-manager: Ingress resources]
* https://cert-manager.io/docs/reference/annotations/#acme-cert-manager-io-http01-edit-in-place[cert-manager: `http01-edit-in-place` annotation]
* https://cert-manager.io/docs/usage/gateway/[cert-manager: Gateway resources]
* https://github.com/cilium/cilium/issues/35347[Cilium issue #35347: HTTPS enforcement with multiple `Ingress` resources]
* https://github.com/cilium/cilium/pull/46303[Cilium PR #46303: `ListenerSet` support]
* https://github.com/cilium/cilium/pull/46184[Cilium PR #46184: `TCPRoute` and `UDPRoute` support]
