= Minor upgrade

[abstract]
This page documents the steps which are necessary to perform Talos and Kubernetes minor version upgrades for a VSHN Managed Talos cluster.

[NOTE]
====
This page is work in progress and may change without prior notice.
====

== Prerequisites

* A local `gandalf` installation
* Access to the Project Syn tenant repo
* Admin access to the target cluster

== Steps

. Clone the workflow repository
+
[NOTE]
====
You can use an existing checkout of the workflows repo.
If you, make sure that you fetch the latest changes.
====
+
[source,bash]
----
git clone git@github.com:vshn/managed-talos-workflows
----

. Run the Gandalf "cloudscale-upgrade" workflow
+
[TIP]
====
The workflow supports updating the cluster's Kubernetes and Talos versions.

The workflow queries the cluster for the current versions, and the Talos support matrix for the target Talos and Kubernetes version compatibility.
====
+
[TIP]
====
We recommend running this step in an empty directory.
The workflow will compile the cluster catalog in the working directory.
====
+
[source,bash]
----
WORKFLOW_DIR=./managed-talos-workflows <1>
# Run upgrade workflow
gandalf run "${WORKFLOW_DIR}/cloudscale-upgrade.workflow" \
  ${WORKFLOW_DIR}/cloudscale/*.yml
  ${WORKFLOW_DIR}/shared/*.yml
----
<1> Adjust this variable to point to the workflow repository checkout.

. Wait for the upgrade to complete.
You can observe the upgrade on the cluster.
+
TIP: Cluster API will replace all machines when performing a Kubernetes upgrade or a Talos minor upgrade with a new base image.
+
.Check Cluster API machines
[source,bash]
----
kubectl -n syn-cluster-api get machine -w
----
+
.Check nodes
[source,bash]
----
kubectl get nodes -w
----
